# Generated by Django 5.0.6 on 2024-07-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False, verbose_name='DNI')),
                ('studentName', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('phone', models.IntegerField(verbose_name='Teléfono')),
                ('responsible', models.CharField(max_length=100, null=True, verbose_name='Responsable')),
                ('startDate', models.DateField(verbose_name='Fecha de Inicio')),
                ('orienteer', models.CharField(max_length=100, verbose_name='Orientador')),
                ('medicalFile', models.CharField(max_length=100, verbose_name='Ficha Médica')),
                ('dniImage', models.ImageField(null=True, upload_to='images/', verbose_name='Foto del DNI')),
                ('status', models.CharField(max_length=100, verbose_name='Estado')),
                ('comments', models.TextField(null=True, verbose_name='Comentarios')),
                ('actionPlan', models.TextField(null=True, verbose_name='Plan de Acción')),
            ],
        ),
    ]
